# Generated by Django 2.1 on 2020-04-25 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fuel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FuelRequistion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved_by', models.CharField(max_length=255)),
                ('recieved_by', models.CharField(max_length=255)),
                ('amount_requested', models.FloatField()),
                ('amount_approved', models.FloatField()),
                ('purpose', models.CharField(max_length=255)),
                ('current_milage', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='RequisitionStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requisition_status', models.CharField(max_length=255)),
            ],
        ),
    ]
