# Generated by Django 2.1 on 2020-04-25 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicle', '0001_initial'),
        ('fuelmanagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelrequistion',
            name='registration_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='vehicle.Vehicle'),
        ),
        migrations.AddField(
            model_name='fuelrequistion',
            name='requisition_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fuelmanagement.RequisitionStatus'),
        ),
        migrations.AddField(
            model_name='fuelrequistion',
            name='vehicle_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.VehicleModel'),
        ),
    ]
