# Generated by Django 2.1 on 2020-05-04 21:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fuelmanagement', '0002_auto_20200425_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelrequistion',
            name='approved_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fuelrequistion',
            name='recieved_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='recieved_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
