# Generated by Django 2.1 on 2020-05-10 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fuelmanagement', '0004_auto_20200505_0000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fuelrequistion',
            name='vehicle_model',
        ),
        migrations.AddField(
            model_name='fuelrequistion',
            name='approval_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='fuelrequistion',
            name='requestor',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.DO_NOTHING,
                                    related_name='requested_by', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fuelrequistion',
            name='amount_approved',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='fuelrequistion',
            name='amount_requested',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
        migrations.AlterField(
            model_name='fuelrequistion',
            name='approved_by',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fuelrequistion',
            name='fuel_recieved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING,
                                    related_name='recieved_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
