# Generated by Django 2.1 on 2020-05-10 20:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fuelmanagement', '0007_auto_20200510_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelrequistion',
            name='requestor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='requested_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
