# Generated by Django 2.1 on 2020-05-10 20:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fuelmanagement', '0008_auto_20200510_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelrequistion',
            name='requstion_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
