# Generated by Django 2.1 on 2020-05-15 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fuelmanagement', '0011_auto_20200512_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelrequisition',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='account.UserProfile'),
        ),
    ]
