# Generated by Django 2.1 on 2020-05-15 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fuelmanagement', '0012_auto_20200515_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelrequisition',
            name='requestor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='requested_by', to='account.UserProfile'),
        ),
    ]
