# Generated by Django 2.1 on 2020-05-15 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fuelmanagement', '0013_auto_20200515_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelrequisition',
            name='fuel_recieved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='recieved_by', to='account.UserProfile'),
        ),
    ]
