# Generated by Django 2.1 on 2020-05-15 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fuelmanagement', '0015_auto_20200515_2247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fuelrequisition',
            name='approved_by',
        ),
    ]
