# Generated by Django 2.1 on 2020-05-15 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200502_2110'),
        ('fuelmanagement', '0016_remove_fuelrequisition_approved_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelrequisition',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='account.UserProfile'),
        ),
    ]
