# Generated by Django 2.1 on 2020-05-16 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fuelmanagement', '0017_fuelrequisition_approved_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelrequisition',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fuelrequisition',
            name='requestor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='requested_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
